#pragma once
#include <string>

enum class TokenType {
    IMPORT, FROM, AS, VAR, LET, FN, IF, ELSE, WHILE, FOR, RETURN, BREAK, CONTINUE, TRUE, FALSE, NULL_T,
    TRY, CATCH, FINALLY, ASYNC, AWAIT, IN, SWITCH, CASE, DEFAULT,
    THROW, STRUCT, ENUM, INTERFACE, IMPL,
    IDENTIFIER, STRING, TEMPLATE_STRING, NUMBER,
    EQUALS, EQUAL_EQUAL, BANG_EQUAL, LT, LTE, GT, GTE,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    PLUS_EQUALS, MINUS_EQUALS, STAR_EQUALS, SLASH_EQUALS, PERCENT_EQUALS,
    PLUS_PLUS, MINUS_MINUS,
    BANG, AND_AND, OR_OR,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    COMMA, SEMICOLON, COLON, DOT, DOT_DOT_DOT,
    ARROW_LOG,
    QUESTION, QUESTION_DOT, QUESTION_QUESTION,
    EOF_TYPE
};

struct Token {
    TokenType type;
    std::string value;
    int line;
    int col;
};

